version: "3"

services:

  mail:
    image: djfarrelly/maildev
    restart: unless-stopped
    ports:
      - 1025:25
      - 1080:80
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password # username: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432

  app:
    build: .
    command: /start-reload.sh
    depends_on:
     - db
     - mail
    ports:
      - 80:80
    volumes:
     - ${PWD}/:/app
    #  - ${HOME}/.aws:/root/.aws
    # environment:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    