version: "3"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password # username: postgres
      POSTGRES_DB: master
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
     - db
    ports:
      - 80:80
    volumes:
     - ${PWD}/:/app
    #  - ${HOME}/.aws:/root/.aws
    # environment:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY